function [F,J] = par2F(f)
%PAR2F Return a fundamental matrix and its jacobian from parameters

f1 = f(1); f2 = f(2); f3 = f(3); f4 = f(4); f5 = f(5); f6 = f(6); f7 = f(7);

F = reshape(ang2cart([f1;f2;f3]),2,2);
F(3,:) = f4*F(1,:) + f5*F(2,:);
F(:,3) = f6*F(:,1) + f7*F(:,2);

% Jacobian (from Symbolic Toolbox)
J = [
                                                                                       -sin(f1),                                                                                              0,                                                                                              0,                                                                                              0,                                                                                              0,                                                                                              0,                                                                                              0
                                                                                cos(f1)*cos(f2),                                                                               -sin(f1)*sin(f2),                                                                                              0,                                                                                              0,                                                                                              0,                                                                                              0,                                                                                              0
                                                                 -f4*sin(f1)+f5*cos(f1)*cos(f2),                                                                            -f5*sin(f1)*sin(f2),                                                                                              0,                                                                                        cos(f1),                                                                                sin(f1)*cos(f2),                                                                                              0,                                                                                              0
                                                                        cos(f1)*sin(f2)*cos(f3),                                                                        sin(f1)*cos(f2)*cos(f3),                                                                       -sin(f1)*sin(f2)*sin(f3),                                                                                              0,                                                                                              0,                                                                                              0,                                                                                              0
                                                                        cos(f1)*sin(f2)*sin(f3),                                                                        sin(f1)*cos(f2)*sin(f3),                                                                        sin(f1)*sin(f2)*cos(f3),                                                                                              0,                                                                                              0,                                                                                              0,                                                                                              0
                                          f4*cos(f1)*sin(f2)*cos(f3)+f5*cos(f1)*sin(f2)*sin(f3),                                          f4*sin(f1)*cos(f2)*cos(f3)+f5*sin(f1)*cos(f2)*sin(f3),                                         -f4*sin(f1)*sin(f2)*sin(f3)+f5*sin(f1)*sin(f2)*cos(f3),                                                                        sin(f1)*sin(f2)*cos(f3),                                                                        sin(f1)*sin(f2)*sin(f3),                                                                                              0,                                                                                              0
                                                         -f6*sin(f1)+f7*cos(f1)*sin(f2)*cos(f3),                                                                     f7*sin(f1)*cos(f2)*cos(f3),                                                                    -f7*sin(f1)*sin(f2)*sin(f3),                                                                                              0,                                                                                              0,                                                                                        cos(f1),                                                                        sin(f1)*sin(f2)*cos(f3)
                                                  f6*cos(f1)*cos(f2)+f7*cos(f1)*sin(f2)*sin(f3),                                                 -f6*sin(f1)*sin(f2)+f7*sin(f1)*cos(f2)*sin(f3),                                                                     f7*sin(f1)*sin(f2)*cos(f3),                                                                                              0,                                                                                              0,                                                                                sin(f1)*cos(f2),                                                                        sin(f1)*sin(f2)*sin(f3)
 f6*(-f4*sin(f1)+f5*cos(f1)*cos(f2))+f7*(f4*cos(f1)*sin(f2)*cos(f3)+f5*cos(f1)*sin(f2)*sin(f3)),              -f6*f5*sin(f1)*sin(f2)+f7*(f4*sin(f1)*cos(f2)*cos(f3)+f5*sin(f1)*cos(f2)*sin(f3)),                                    f7*(-f4*sin(f1)*sin(f2)*sin(f3)+f5*sin(f1)*sin(f2)*cos(f3)),                                                          f6*cos(f1)+f7*sin(f1)*sin(f2)*cos(f3),                                                  f6*sin(f1)*cos(f2)+f7*sin(f1)*sin(f2)*sin(f3),                                                                  f4*cos(f1)+f5*sin(f1)*cos(f2),                                          f4*sin(f1)*sin(f2)*cos(f3)+f5*sin(f1)*sin(f2)*sin(f3)];
 
 
end

